//! Discovery report generation.
//!
//! Produces a Markdown report summarizing what was found during discovery:
//! routes, pages, flows, tests generated, health score.

use super::DiscoverResult;
use super::generator::{ExploredPage, PageStatus};
use std::path::Path;

/// Generate and write the discover report to `.rayo/discover-report.md`.
pub fn write_report(
    result: &DiscoverResult,
    pages: &[ExploredPage],
    report_path: &Path,
) -> Result<(), std::io::Error> {
    let content = generate_report(result, pages);
    if let Some(parent) = report_path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(report_path, content)
}

/// Generate the Markdown report content.
fn generate_report(result: &DiscoverResult, pages: &[ExploredPage]) -> String {
    let mut md = String::new();

    // Header
    md.push_str("# rayo discover report\n\n");

    // Summary
    md.push_str("## Summary\n\n");
    md.push_str("| Metric | Value |\n");
    md.push_str("|--------|-------|\n");
    md.push_str(&format!("| Framework | {} |\n", result.framework));
    md.push_str(&format!(
        "| Routes (code) | {} |\n",
        result.routes_from_code
    ));
    md.push_str(&format!(
        "| Routes (explored) | {} |\n",
        result.routes_explored
    ));
    md.push_str(&format!("| Flows detected | {} |\n", result.flows_detected));
    md.push_str(&format!(
        "| Tests generated | {} |\n",
        result.tests_generated
    ));
    md.push_str(&format!("| Tests passed | {} |\n", result.tests_passed));
    md.push_str(&format!("| Tests failed | {} |\n", result.tests_failed));
    md.push_str(&format!("| Console errors | {} |\n", result.console_errors));
    md.push_str(&format!("| Health score | {}% |\n", result.health_score));
    md.push_str(&format!("| Duration | {}ms |\n", result.duration_ms));
    md.push('\n');

    // Health score bar
    md.push_str("## Health Score\n\n");
    md.push_str(&format!("**{}**/100\n\n", result.health_score));
    md.push_str(&health_bar(result.health_score));
    md.push_str("\n\n");

    // Pages explored
    md.push_str("## Pages Explored\n\n");
    md.push_str("| URL | Status | Console Errors | Has Elements |\n");
    md.push_str("|-----|--------|----------------|---------------|\n");
    for page in pages {
        let status_icon = match page.status {
            PageStatus::Ok => "ok",
            PageStatus::Error => "ERROR",
            PageStatus::Redirect => "redirect",
            PageStatus::AuthGated => "auth-gated",
        };
        md.push_str(&format!(
            "| {} | {} | {} | {} |\n",
            page.url,
            status_icon,
            page.console_errors,
            if page.has_elements { "yes" } else { "no" }
        ));
    }
    md.push('\n');

    // Console errors
    let total_console_errors: usize = pages.iter().map(|p| p.console_errors).sum();
    if total_console_errors > 0 {
        md.push_str("## Console Errors\n\n");
        md.push_str(&format!(
            "Found **{total_console_errors}** console error(s) across **{}** page(s).\n\n",
            pages.iter().filter(|p| p.console_errors > 0).count()
        ));
    }

    // Test results
    md.push_str("## Test Results\n\n");
    md.push_str(&format!(
        "- Generated: **{}** test files\n",
        result.tests_generated
    ));
    md.push_str(&format!("- Passed: **{}**\n", result.tests_passed));
    md.push_str(&format!("- Failed: **{}**\n", result.tests_failed));
    md.push('\n');

    md.push_str("---\n");
    md.push_str("*Generated by `rayo-ui discover`*\n");

    md
}

/// Compute health score from exploration data.
pub fn compute_health_score(pages: &[ExploredPage], total_code_routes: usize) -> u32 {
    if pages.is_empty() {
        return 0;
    }

    // Console score: 0 errors=100, 1-3=70, 4-10=40, 10+=10
    let total_console_errors: usize = pages.iter().map(|p| p.console_errors).sum();
    let console_score: f64 = match total_console_errors {
        0 => 100.0,
        1..=3 => 70.0,
        4..=10 => 40.0,
        _ => 10.0,
    };

    // Accessibility score: pages with elements / total pages
    let pages_with_elements = pages.iter().filter(|p| p.has_elements).count();
    let empty_pages = pages.len() - pages_with_elements;
    let accessibility_score = if pages.is_empty() {
        0.0
    } else {
        let base = (pages_with_elements as f64 / pages.len() as f64) * 100.0;
        (base - (empty_pages as f64 * 20.0)).max(0.0)
    };

    // Routes score: code routes that loaded successfully / total code routes
    let ok_pages = pages.iter().filter(|p| p.status == PageStatus::Ok).count();
    let routes_score = if total_code_routes == 0 {
        if ok_pages > 0 { 100.0 } else { 50.0 }
    } else {
        (ok_pages.min(total_code_routes) as f64 / total_code_routes as f64) * 100.0
    };

    // Forms score: assume labeled if page has elements (simplified)
    let forms_score = accessibility_score; // Use same heuristic

    // Weighted average
    let score = console_score * 0.25
        + accessibility_score * 0.25
        + routes_score * 0.25
        + forms_score * 0.25;

    score.round().clamp(0.0, 100.0) as u32
}

/// Generate a text-based health bar.
fn health_bar(score: u32) -> String {
    let filled = (score as usize) / 5;
    let empty = 20 - filled;
    let bar: String = "=".repeat(filled) + &" ".repeat(empty);

    let color_label = if score >= 80 {
        "Healthy"
    } else if score >= 50 {
        "Needs Attention"
    } else {
        "Critical"
    };

    format!("`[{bar}]` {score}% - {color_label}")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_compute_health_score_perfect() {
        let pages = vec![
            ExploredPage {
                url: "/".into(),
                status: PageStatus::Ok,
                console_errors: 0,
                has_elements: true,
            },
            ExploredPage {
                url: "/about".into(),
                status: PageStatus::Ok,
                console_errors: 0,
                has_elements: true,
            },
        ];
        assert_eq!(compute_health_score(&pages, 2), 100);
    }

    #[test]
    fn test_compute_health_score_with_errors() {
        let pages = vec![ExploredPage {
            url: "/".into(),
            status: PageStatus::Ok,
            console_errors: 5,
            has_elements: true,
        }];
        let score = compute_health_score(&pages, 1);
        assert!(score < 100);
        assert!(score > 0);
    }

    #[test]
    fn test_compute_health_score_empty() {
        assert_eq!(compute_health_score(&[], 0), 0);
    }
}
